language: cpp
compiler: g++

before_install:
  - sudo add-apt-repository ppa:codegear/release -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq premake4 gcc-4.8 g++-4.8 gcc-4.8-multilib g++-4.9-multilib
  - sudo apt-get --yes install mono-complete
  - export CXX="g++-4.8"
  
before_script:
  - premake4 gmake

script:
  - make CXX=g++-4.8 config=release32
