language: cpp
compiler: g++

before_install:
  - sudo add-apt-repository ppa:codegear/release -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq premake4 gcc g++ mono-complete

before_script:
  - premake4 gmake

script:
  - make config=release64

addons:
  artifacts:
    paths:
    - $(ls bin/*.so | tr "\n" ":")